name: Release
on:
  release:
    types: [created]

env:
  CARGO_INCREMENTAL: 0  # Disable incremental for release builds
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_name: chess_game
            output_name: chess_game-linux-x86_64
            linker: mold
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: chess_game.exe
            output_name: chess_game-windows-x86_64.exe
            linker: lld

    steps:
      - uses: actions/checkout@v4

      # Setup cache for cargo registry and target directory
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          components: rust-src, llvm-tools-preview  # Required for LLD

      # Linux-specific optimizations
      - name: Install mold and musl-tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools mold
          sudo ln -sf /usr/bin/mold /usr/bin/ld

      # Windows-specific optimizations
      - name: Configure LLD linker (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "[target.x86_64-pc-windows-msvc]" >> .cargo/config.toml
          echo "linker = \"rust-lld.exe\"" >> .cargo/config.toml

      # Build with optimizations
      - name: Build Release Binary
        run: |
          cargo build --release --target ${{ matrix.target }} -- -C link-arg=-fuse-ld=${{ matrix.linker }} $RUSTFLAGS

      - name: Prepare Artifact
        shell: bash
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/${{ matrix.binary_name }} dist/${{ matrix.output_name }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: dist/${{ matrix.output_name }}

  release:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
